alias: "Den motion light off"
trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor_158d00010a9ef1
  to: 'off'
  for:
    minutes: 5
condition:
- condition: state
  entity_id: light.denceiling
  state: 'on'
action:
  service: homeassistant.turn_off
  entity_id: light.denceiling
