alias: "Den motion light on"
trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor_158d00010a9ef1
  state: 'on'
#condition:
#  - condition: numeric_state
#    entity_id: sensor.entrance_multisensor_luminance_11_3
#    below: 30
action:
  service: homeassistant.turn_on
  entity_id: light.denceiling
