- alias: 'doorbell'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.doorbell
    from: '0'
    to: '1'
  action:
    - service: xiaomi.play_ringtone
      data:
        gw_mac: f0:b4:29:cc:36:60
        ringtone_id: 10
        ringtone_vol: 8
    - service: notify.telegram
      data:
        title: Doorbell
        message: 'Ringklockan ringer'
        data:
          photo:
          - url: !secret doorcam_url
            username: visitor
            password: !secret doorcam_pw
    - service: notify.livingroom_tv
      data:
        message: "Någon ringer på dörren"
    - delay: 0:00:05
    - service: notify.telegram
      data:
        title: Doorbell
        message: 'Ringklockan ringer'
        data:
          photo:
          - url: !secret doorcam_url
            username: visitor
            password: !secret doorcam_pw
    - delay: 0:00:05
    - service: notify.telegram
      data:
        title: Doorbell
        message: 'Ringklockan ringer'
        data:
          photo:
          - url: !secret doorcam_url
            username: visitor
            password: !secret doorcam_pw