- !include automation/sunset.yaml
- !include automation/sunrise.yaml
- !include automation/entrance_light.yaml
- !include automation/bathroom_fan_on.yaml
- !include automation/bathroom_fan_off.yaml
- !include automation/bathroom_motion_off.yaml
- !include automation/bathroom_motion_on.yaml
- !include automation/bathroom_fan_off_notification.yaml
- !include automation/bathroom_fan_on_notification.yaml

