- action:
  - data:
      entity_id: switch.bathroom_lights_switch
    service: homeassistant.turn_on
  - data:
      entity_id: scene.bath_night
    service: scene.turn_on
  alias: Bathroom motion night
  condition:
  - after: '23:59'
    before: 04:00
    condition: time
  id: '1502619491737'
  trigger:
  - entity_id: binary_sensor.bathroom_multisensor_sensor_10_0
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: cover.livingroom_blinds_level
    service: cover.open_cover
  alias: Open Blinds - Sun below horizon
  condition:
  - condition: state
    entity_id: cover.livingroom_blinds_level
    state: closed
  id: '1502630013284'
  trigger:
  - entity_id: sun.sun
    from: above_horizon
    platform: state
    to: below_horizon
- action:
  - data:
      entity_id: switch.bathroom_lights_switch
    service: homeassistant.turn_on
  - data:
      entity_id: scene.bath_bright
    service: scene.turn_on
  alias: Bathroom motion dark
  condition:
  - after: 04:00
    before: '23:59'
    condition: time
  id: '1502631695144'
  trigger:
  - entity_id: binary_sensor.bathroom_multisensor_sensor_10_0
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.bathroom_lights_switch
    service: homeassistant.turn_on
  - data:
      entity_id: scene.bath_day
    service: scene.turn_on
  alias: Bathroom motion light
  condition:
  - after: 04:00
    before: '23:59'
    condition: time
  - above: '70'
    below: '10000'
    condition: numeric_state
    entity_id: sensor.bathroom_multisensor_luminance_10_3
    value_template: ''
  id: '1502631862387'
  trigger:
  - entity_id: binary_sensor.bathroom_multisensor_sensor_10_0
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: scene.bath_bright
    service: scene.turn_on
  - data:
      entity_id: switch.bathroom_fan_switch
    service: homeassistant.turn_on
  alias: Bathroom_button_singleclick
  condition: []
  id: '1504594657350'
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d000186e5cd
    event_type: click
    platform: event
- action:
  - data:
      entity_id: switch.bathroom_fan_switch
    service: homeassistant.turn_off
  - data:
      entity_id: group.bathroom_lamps
    service: light.turn_off
  alias: Bathroom_button_longclick
  condition: []
  id: '1504594841729'
  trigger:
  - event_data:
      click_type: hold
      entity_id: binary_sensor.switch_158d000186e5cd
    event_type: click
    platform: event
- id: 'updates123'
  alias: 'Update Available Notifications'
  trigger:
  -  platform: state
     entity_id: updater.updater
  action:
  - service: notify.slack
    data:
      message: '@johan - Update for Home Assistant is available.'      
