- !include automation/2130.yaml
- !include automation/2300.yaml
- !include automation/bathoff.yaml
- !include automation/bathroom_motion.yaml
- !include automation/batteries.yaml
- !include automation/doorbell.yaml
- !include automation/entrance_light_motion.yaml
- !include automation/entrance_light_timer.yaml
- !include automation/kitchenlights.yaml
- !include automation/kitchenlights_off.yaml
- !include automation/morning.yaml
- !include automation/sunrise.yaml
- !include automation/sunset.yaml
- !include automation/updater.yaml
- !include automation/cube90.yaml
- !include automation/cube180.yaml
- !include automation/cubemove.yaml
- !include automation/cubetaptwice.yaml
#- !include automation/cubealert.yaml
- !include automation/cubefreefall.yaml
- !include automation/cuberotate.yaml
- !include automation/cubeshakeair.yaml
- !include automation/cubeswing.yaml
- !include automation/den_light_motion.yaml
- !include automation/den_light_timer.yaml

#- !include test.yaml
