homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 142
  temperature_unit: C
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

group: !include group.yaml
sensor: !include_dir_merge_list sensors
camera: !include cameras.yaml
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 60000

frontend:
http:
  api_password: !secret http_password

updater:
discovery:
conversation:
history:
logbook:
sun:

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret pi_username
  password: !secret pi_password

device_tracker:
  platform: nmap_tracker
  hosts: !secret track_hosts
  track_new_devices: no
  consider_home: 1800

weblink: !include weblinks.yaml
panel_iframe: !include panel_iframe.yaml
