homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 142
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

group: !include group.yaml
sensor: !include_dir_merge_list sensors
camera: !include cameras.yaml
zwave: !include zwave.yaml
frontend:
http:
  api_password: !secret http_password

updater:
discovery:
conversation:
history:
logbook:
sun:
mqtt: !include mqtt.yaml

device_tracker:
  platform: nmap_tracker
  hosts: !secret track_hosts
  track_new_devices: no
  consider_home: 1800

weblink: !include weblinks.yaml
panel_iframe: !include panel_iframe.yaml

automation: !include automation.yaml
script: !include scripts.yaml

light:
  platform: osramlightify
  host: !secret lightify_ip

scene: !include_dir_list scenes
