homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 142
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

config:
#group: !include groups.yaml
group: !include group.yaml
zwave: !include zwave.yaml
#zwave:
#  device_config: !include zwave_device_config.yaml

sensor: !include_dir_merge_list sensors
camera: !include cameras.yaml

frontend:
http:
  api_password: !secret http_password

emulated_hue:
#  type: alexa
  host_ip: !secret ha_ip
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - scene
    - switch
    - light
updater:
discovery:
conversation:
history:
  include:
    domains:
      - sensor
      - switch
    entities:
      - device_tracker.johan_iphone
      - switch.bathroom_lights_switch_23_0
  exclude:
    entities:
      - sensor.diningroom_light_alarm_type_14_0
recorder:
  db_url: !secret mysql_url
  purge_days: 30
logbook:
  include:
    domains:
      - switch
      - sun
      - media_player
      - automation
      - device_tracker
    entities:
      - sensor.doorbell
      - switch.bathroom_lights_switch_23_0
sun:
mqtt: !include mqtt.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: !secret track_hosts
    track_new_devices: no
    consider_home: 1800
  - platform: trackr
    username: !secret email
    password: !secret trackr_pw

panel_iframe: !include panel_iframe.yaml

automation: !include_dir_merge_list automation/
#script: !include scripts.yaml

light:
  - platform: osramlightify
    host: !secret lightify_ip
  - platform: yeelight
    devices:
      !secret yeelight1_ip:
        name: Den.Ceiling
      !secret yeelight2_ip:
        name: Bathroom.shower

scene: !include_dir_list scenes

tellstick:
  signal_repetitions: 5

switch:
  - platform: tellstick
  - platform: mqtt
    name: "Leaf Climate"
    command_topic: "leaf/control/climate"
    payload_on: "1"
    payload_off: "0"
  - platform: mqtt
    name: "Leaf Update"
    command_topic: "leaf/control/update"
    payload_on: "1"
    payload_off: "0"
#    icon: mdi:update
#  - platform: rest
#  - platform: rest
#    resource: http://127.0.0.1:1234/park
#  - platform: rest
#    resource: http://127.0.0.1:1234/stop
#  - platform: rest
#    resource: http://127.0.0.1:1234/start

battery_state:

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api
    default_channel: '#skarsjo'
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api
    chat_id: !secret telegram_chatid
  - name: iOSApp
    platform: ios
    target: !secret ios_token

media_player:
  - platform: squeezebox
    host: !secret squeezebox_ip
    port: 9000
  - platform: apple_tv
    host: !secret bedroom_apple_ip
    login_id: !secret bedroom_apple_id

#zoneminder:
#  host: !secret zm_ip
#  username: admin
#  password: !secret skarsjopass

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

xiaomi:
  gateways:
    - sid:
      key: !secret xiaomi_key

ios:

zone:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  radius: 250
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 250
  icon: mdi:castle