homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 142
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

group: !include group.yaml
sensor: !include_dir_merge_list sensors
camera: !include cameras.yaml
zwave: !include zwave.yaml
frontend:
http:
  api_password: !secret http_password

emulated_hue:
  type: alexa
  host_ip: !secret ha_ip
  listen_port: 8300
  expose_by_default: true
  exposed_domains:
    - scene
    - switch
    - light
updater:
discovery:
conversation:
history:
  include:
    domains:
      - sensor
      - switch
    entities:
      - device_tracker.johan_iphone
  exclude:
    entities:
      - sensor.diningroom_light_alarm_type_14_0
recorder:
  db_url: !secret mysql_url
  purge_days: 30
logbook:
  include:
    domains:
      - sun
      - media_player
      - automation
      - device_tracker
    entities:
      - sensor.doorbell
sun:
mqtt: !include mqtt.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: !secret track_hosts
    track_new_devices: no
    consider_home: 1800
  - platform: trackr
    username: !secret email
    password: !secret trackr_pw

weblink: !include weblinks.yaml
panel_iframe: !include panel_iframe.yaml

automation: !include automation.yaml
script: !include scripts.yaml

light:
  - platform: osramlightify
    host: !secret lightify_ip
  - platform: yeelight
    devices:
      10.11.12.26:
        name: Den.Ceiling

scene: !include_dir_list scenes

tellstick:
  signal_repetitions: 5

switch:
  - platform: tellstick
#  - platform: rest
#    resource: http://127.0.0.1:1234/park
#  - platform: rest
#    resource: http://127.0.0.1:1234/stop
#  - platform: rest
#    resource: http://127.0.0.1:1234/start

battery_state:

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api
    default_channel: '#skarsjo'
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api
    chat_id: !secret telegram_chatid

media_player:
  - platform: squeezebox
    host: !secret squeezebox_ip
    port: 9000

zoneminder:
  host: !secret zm_ip
  username: admin
  password: !secret skarsjopass

tts:
  - platform: google
