homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 142
  unit_system: metric
#  temperature_unit: C
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

group: !include group.yaml
sensor: !include_dir_merge_list sensors
camera: !include cameras.yaml

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 60000

frontend:
http:
  api_password: !secret http_password

updater:
discovery:
conversation:
history:
logbook:
sun:

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret pi_username
  password: !secret pi_password

device_tracker:
  platform: nmap_tracker
  hosts: !secret track_hosts
  track_new_devices: no
  consider_home: 1800

weblink: !include weblinks.yaml
panel_iframe: !include panel_iframe.yaml

automation:
  trigger:
    platform: sun
    event: sunset
    offset: "-00:30:00"
  action:
    service: switch.turn_on
    entity_id: switch.entrance_porch_light_switch_2_2

automation 2:
  trigger:
    platform: sun
    event: sunrise
    offset: "00:30:00"
  action:
    service: switch.turn_off
    entity_id: switch.entrance_porch_light_switch_2_2

automation 3:
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_multisensor_sensor_10
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: script.timed_lamp

script:
  timed_lamp:
    alias: "Turn on lamp and set timer"
    sequence:
      # Cancel ev. old timers
      - service: script.turn_off
        data:
           entity_id: script.timer_off
      - service: switch.turn_on
        data:
          entity_id: switch.bathroom_fan_switch_4
      # Set new timer
      - service: script.turn_on
        data:
          entity_id: script.timer_off

  timer_off:
    alias: "Turn off lamp after 10 minutes"
    sequence:
      - delay:
          minutes: 5
      - service: switch.turn_off
        data:
          entity_id: switch.bathroom_fan_switch_4
