homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 142
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "automation.disabled*":
      hidden: true
    "*.*":
      custom_ui_state_card: state-card-custom-ui
        #turn device trackers into badges in groups
    "device_tracker.*":
      state_card_mode: badges
  packages: !include_dir_named packages


cloud:
shell_command: !include_dir_merge_named shell_commands/
config:
group: !include group.yaml
zwave: !include zwave.yaml


sensor: !include_dir_merge_list sensors
camera: !include cameras.yaml

frontend:
  javascript_version: latest

http:
  api_password: !secret http_password
  base_url: http://localhost:8123

#emulated_hue:
#  type: alexa
#  host_ip: !secret ha_ip
#  listen_port: 8300
#  expose_by_default: true
#  exposed_domains:
#    - scene
#    - light
updater:
  include_used_components: true
discovery:
conversation:

######################### LOGGING #########################
history:
  include:
    domains:
      - sensor
      - switch
      - zwave
    entities:
      - device_tracker.johan_iphone
      - switch.bathroom_lights_switch_23_0
  exclude:
    entities:
      - sensor.diningroom_light_alarm_type_14_0

recorder:
  db_url: !secret mysql_url

logbook:
#  include:
#    domains:
#      - switch
#      - sun
#      - media_player
#      - automation
#      - device_tracker
#    entities:
#      - sensor.doorbell
#      - switch.bathroom_lights_switch_23_0
#      - binary_sensor.bathroom_multisensor_sensor_10_0

logger: !include logger.yaml

influxdb:
  host: !secret influxip
  database: home_assistant
  max_retries: 10
######################### /LOGGING ########################

sun:
mqtt: !include mqtt.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: !secret track_hosts
    track_new_devices: no
    consider_home: 1800
    interval_seconds: 30
  - platform: trackr
    username: !secret email
    password: !secret trackr_pw

panel_iframe: !include panel_iframe.yaml

automation: !include automations.yaml
automation old: !include_dir_merge_list automation/

light:
  - platform: osramlightify
    host: !secret lightify_ip
  - platform: yeelight
    devices:
      !secret yeelight3_ip:
        name: Den.Ceiling
      !secret yeelight2_ip:
        name: Bathroom.shower
      !secret yeelight4_ip:
        name: Showerroom.shower
      !secret yeelight1_ip:
        name: Showerroom
      !secret yeelight5_ip:
        name: Pantry
      !secret yeelight_strip_ip:
        name: Basement.hallway
  - platform: tellstick

scene: !include_dir_list scenes

tellstick:
  signal_repetitions: 5

switch:
  - platform: tellstick
  - platform: broadlink
    host: 10.11.12.23
    mac: '34:ea:34:b2:f7:fd'
    type: rm_mini
    switches:
      livingroom_receiver_power:
        friendly_name: "Pioneer Reciever Power"
        command_on: 'JgDQAgABF4sRNBEREjMSERASEjMSEBIzExARNBASEDUSMxIQETQTEBEREhASMxIzEjMSERASEBMRNA81ERIQEhESEjISMxMyEgADcwABFYwSMxIRETQRERASEjMREhEzEhESMxIQETQSMxIREjITEBIQEhEQNRA1EzIRERIQERIRNBMyERESEBIREDUQNRA0EQADUgABFYwRNREREjMSEBESEjMRERIzEhARNBIRETQQNBISEDQRERESEBIRNBIzEjMSEBIREhARNQ81EBMQEhEREjMSMxIzEgADcwABGIoSMxEREjMTDxIRETQSEBIzERERNBIRETQRNBEREjMSEBIREBISMxE0ETQQExASERESMxIzEhERERIREDQRNBIzEQADTgABGY0RMxIREDUQExASEDUSEBIzEhERMxIREjMRNBEREjMQExASERESMxE0EjMSERASEw8SMxIzERIQEhATEDUSMhE0EgADcwABFowSMxIREDUREREREjMSERE0EBMQNBESEDQRNBIREjMSEBMQEBIRNBIzEjMRERIREBMPNRA1EhERERIQEjMSMxIzEwADUAABFY0SMxEREjMSEBIREDUREhA0EhESMxEREjMSMxIQEjMSERERERIQNRE0EDQREhASEhESMxE0ERERERIREjQPNRA1EAADdQABFowRNBASETQSERASEjMSEREzExASMxIQEjMRNBATEDUQEhESERESMxIzEjMSEBIRERESMxIzEBMQEhERETQSMxIzEgADUQABF4sSMxIQEjMSEREREjMRERI0EBISMxEREjMRNBIRETQRERIREBMRMxE0EDUTDxIRERESMxIzEhERERIRETMSMxIzEQADdQABFY0RNBESDzUQExEREjIREhIzEhESMxERETQSMxIQEjMREw8TERESMxIzEjMSEBIREBIRNBE0ERESEhASETQQNBIzEgANBRESERESMxIz'
        command_off: 'JgDQAgABF4sRNBEREjMSERASEjMSEBIzExARNBASEDUSMxIQETQTEBEREhASMxIzEjMSERASEBMRNA81ERIQEhESEjISMxMyEgADcwABFYwSMxIRETQRERASEjMREhEzEhESMxIQETQSMxIREjITEBIQEhEQNRA1EzIRERIQERIRNBMyERESEBIREDUQNRA0EQADUgABFYwRNREREjMSEBESEjMRERIzEhARNBIRETQQNBISEDQRERESEBIRNBIzEjMSEBIREhARNQ81EBMQEhEREjMSMxIzEgADcwABGIoSMxEREjMTDxIRETQSEBIzERERNBIRETQRNBEREjMSEBIREBISMxE0ETQQExASERESMxIzEhERERIREDQRNBIzEQADTgABGY0RMxIREDUQExASEDUSEBIzEhERMxIREjMRNBEREjMQExASERESMxE0EjMSERASEw8SMxIzERIQEhATEDUSMhE0EgADcwABFowSMxIREDUREREREjMSERE0EBMQNBESEDQRNBIREjMSEBMQEBIRNBIzEjMRERIREBMPNRA1EhERERIQEjMSMxIzEwADUAABFY0SMxEREjMSEBIREDUREhA0EhESMxEREjMSMxIQEjMSERERERIQNRE0EDQREhASEhESMxE0ERERERIREjQPNRA1EAADdQABFowRNBASETQSERASEjMSEREzExASMxIQEjMRNBATEDUQEhESERESMxIzEjMSEBIRERESMxIzEBMQEhERETQSMxIzEgADUQABF4sSMxIQEjMSEREREjMRERI0EBISMxEREjMRNBIRETQRERIREBMRMxE0EDUTDxIRERESMxIzEhERERIRETMSMxIzEQADdQABFY0RNBESDzUQExEREjIREhIzEhESMxERETQSMxIQEjMREw8TERESMxIzEjMSEBIREBIRNBE0ERESEhASETQQNBIzEgANBRESERESMxIz'
      livingroom_receiver_squeezebox:
        command_on: 'JgAgAQABFowUMRQPEzEUDxQOEzIREhMxERIQNRQOETQUMRQOEzIUDxQOFA8TDxQxEREREhATEDQUMRQxFDEUDhMyFDEUMRQOFAADcQABFY0UMRASETQSERASETQUDhE0FA8TMhMPFDEUMRMPFDERERESEBIREhA1FA4UDxQOFDEUMRQxEDUQEhE1DzUQNRQOEQADUQABFowQNRQPEzEUDxQOFDEUDxMxERIQNRERETQUMRIREDQUDxMPExATDxQxFA4REhESEDQRNBA1FDEUDhMyEzIUMRMPFAADcQABFowUMRQOFDEUDxIQETUPEhE0FA8UMRMPETQUMRERFDEUDxEREREREhA1FA4REhASETQUMRQxFDEUDhMyFDEUMRASEgANBQAAAAAAAAAA'
        command_off: 'JgAgAQABFowUMRQPEzEUDxQOEzIREhMxERIQNRQOETQUMRQOEzIUDxQOFA8TDxQxEREREhATEDQUMRQxFDEUDhMyFDEUMRQOFAADcQABFY0UMRASETQSERASETQUDhE0FA8TMhMPFDEUMRMPFDERERESEBIREhA1FA4UDxQOFDEUMRQxEDUQEhE1DzUQNRQOEQADUQABFowQNRQPEzEUDxQOFDEUDxMxERIQNRERETQUMRIREDQUDxMPExATDxQxFA4REhESEDQRNBA1FDEUDhMyEzIUMRMPFAADcQABFowUMRQOFDEUDxIQETUPEhE0FA8UMRMPETQUMRERFDEUDxEREREREhA1FA4REhASETQUMRQxFDEUDhMyFDEUMRASEgANBQAAAAAAAAAA'
      livingroom_receiver_atv:
        command_on: 'JgCwAQABF4wUMRQPFDEQEhASETUUDhE0FA4RNBQPEzEUMRQPETQQEhQOEzIRNBQxEjMUDhESFDEUMRASFA8SEQ8TEDQSMxQPEAADdAABFowQNRASEjMUDxQOFDEUDhMyFA8UMRQOFDEQNRQOETQQExASETQUDhMyFA8TDxQxETQQNRQOETQUDxQxFDAUDxQOFAADTwABFYwUMRQPFDETDxQOFDEREhA1EBIRNBQPFDAUMRQPFDETDxQOFDERNBQxEDUQEhESEzIUMRQOExATDxQOEzISMxEREQADdAABFowRNBERFDEREhATDzUUDxA0FA8UMRQOFDERNBIREDQREhATDzUUDxA0FA8UDhQxFDEUMRMPETQREhA1EDQREhQOFAADTwABGIkSMxQPFDEUDhERFDETEBQxEREUMRASETQUMRQPEzIUDhQOFDEUMRE0ETQQEhESETQRNBQOERIQEhQOFDEUMRESEwADcQABFowUMRQOFDEREhASETQUDxA0ERIRNBQOFDEUMRQOFDEREhASETQSERE0Ew8UDhQxFDEUMRQOFDEUDxMyEzEREhESFAANBQAAAAAAAAAA'
        command_off: 'JgCwAQABF4wUMRQPFDEQEhASETUUDhE0FA4RNBQPEzEUMRQPETQQEhQOEzIRNBQxEjMUDhESFDEUMRASFA8SEQ8TEDQSMxQPEAADdAABFowQNRASEjMUDxQOFDEUDhMyFA8UMRQOFDEQNRQOETQQExASETQUDhMyFA8TDxQxETQQNRQOETQUDxQxFDAUDxQOFAADTwABFYwUMRQPFDETDxQOFDEREhA1EBIRNBQPFDAUMRQPFDETDxQOFDERNBQxEDUQEhESEzIUMRQOExATDxQOEzISMxEREQADdAABFowRNBERFDEREhATDzUUDxA0FA8UMRQOFDERNBIREDQREhATDzUUDxA0FA8UDhQxFDEUMRMPETQREhA1EDQREhQOFAADTwABGIkSMxQPFDEUDhERFDETEBQxEREUMRASETQUMRQPEzIUDhQOFDEUMRE0ETQQEhESETQRNBQOERIQEhQOFDEUMRESEwADcQABFowUMRQOFDEREhASETQUDxA0ERIRNBQOFDEUMRQOFDEREhASETQSERE0Ew8UDhQxFDEUMRQOFDEUDxMyEzEREhESFAANBQAAAAAAAAAA'
  - platform: wake_on_lan
    mac_address: !secret office_mac
    host: !secret office_host


battery_state:

notify:
  - name: slack
    platform: slack
    api_key: !secret slack_api
    default_channel: '#skarsjo'
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api
    chat_id: !secret telegram_chatid
  - name: iOSApp
    platform: ios
    target: !secret ios_token
  - platform: webostv
    host: !secret lg_ip
    name: livingroom_tv
    filename: webostv.conf

telegram_bot:
  platform: polling
  api_key: !secret telegram_api
  allowed_chat_ids:
    - !secret telegram_chatid

media_player:
  - platform: squeezebox
    host: !secret squeezebox_ip
    port: 9000
  - platform: plex
  - platform: spotify
    client_id: !secret spot_id
    client_secret: !secret spot_pass
  - platform: webostv
    host: !secret lg_ip
    mac: !secret lg_mac
    name: Livingroom TV
    filename: webostv.conf

apple_tv: !include apple_tv.yaml

tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

xiaomi_aqara:
  gateways:
    - mac:
      key: !secret xiaomi_key

ios:

zone:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  radius: 250
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 250
  icon: mdi:castle


script: !include scripts.yaml

binary_sensor:
  - platform: mqtt
    state_topic: dummy/floorplan/sensor
    name: Floorplan

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

timer:
  timer:

customizer:
  custom_ui: local

hue:
  bridges:
    - host: !secret hue_ip