homeassistant:
  name: Home
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: 142
  temperature_unit: C
  time_zone: Europe/Stockholm

frontend:
http:
  api_password: !secret http_password

updater:
discovery:
conversation:
history:
logbook:
sun:

# Weather Prediction
sensor:
  platform: yr

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret pi_username
  password: !secret pi_password

device_tracker
  platform: nmap_tracker
  hosts: !secret track_hosts
  track_new_devices: no
  consider_home: 1800
