- alias: "Bathroom lights"
  trigger:
    platform: state
    entity_id: switch.bathroom_lights_switch_23_0
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.bathroom_shower_lights_switch_28_0

#todo embryo - koordinera lampor i bad och dusch.. Ej commitat

#    - switch.bathroom_lights_switch_23_0
#    - switch.bathroom_shower_lights_switch_28_0