- alias: "bathroom lights on"
  trigger:
    platform: state
    entity_id: switch.bathroom_lights_switch_23_0
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: group.bathroom_lamps

- alias: "bathroom lights off"
  trigger:
    platform: state
    entity_id: switch.bathroom_lights_switch_23_0
    from: 'on'
    to: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: group.bathroom_lamps

#- alias: "Shower lights on from bath"
#  trigger:
#    platform: state
#    entity_id: switch.bathroom_lights_switch_23_0
#    to: 'on'
#  action:
#    - service: homeassistant.turn_on
#      entity_id: group.bathroom_lamps
#
#- alias: "shower lights off from bath"
#  trigger:
#    platform: state
#    entity_id: switch.bathroom_lights_switch_23_0
#    to: 'off'
#  action:
#    - service: homeassistant.turn_off
#      entity_id: group.bathroom_lamps
#
#- alias: "bath lights on from shower"
#  trigger:
#    platform: state
#    entity_id: switch.bathroom_shower_lights_switch_28_0
#    to: 'on'
#  action:
#    - service: homeassistant.turn_on
#      entity_id: group.bathroom_lamps
#
#- alias: "bath lights off from shower"
#  trigger:
#    platform: state
#    entity_id: switch.bathroom_shower_lights_switch_28_0
#    to: 'off'
#  action:
#    - service: homeassistant.turn_off
#      entity_id: group.bathroom_lamps