- alias: "Shower lights on from bath"
  trigger:
    platform: state
    entity_id: switch.bathroom_lights_switch_23_0
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.bathroom_shower_lights_switch_28_0
    - service: homeassistant.turn_on
      entity_id: light.bathroomshower

- alias: "shower lights off from bath"
  trigger:
    platform: state
    entity_id: switch.bathroom_lights_switch_23_0
    state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.bathroom_shower_lights_switch_28_0
    - service: homeassistant.turn_off
      entity_id: light.bathroomshower

- alias: "bath lights on from shower"
  trigger:
    platform: state
    entity_id: switch.bathroom_shower_lights_switch_28_0
    state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.bathroom_lights_switch_23_0
    - service: homeassistant.turn_on
      entity_id: light.bathroomshower

- alias: "bath lights off from shower"
  trigger:
    platform: state
    entity_id: switch.bathroom_shower_lights_switch_28_0
    state: 'off'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.bathroom_lights_switch_23_0
    - service: homeassistant.turn_off
      entity_id: light.bathroomshower

#todo embryo - koordinera lampor i bad och dusch.. Ej commitat

#    - switch.bathroom_lights_switch_23_0
#    - switch.bathroom_shower_lights_switch_28_0