#Available actions are flip90, flip180, move, tap_twice, shake_air, swing, alert, free_fall and rotate 

alias: 'cube shakeair'
trigger:
  platform: event
  event_type: cube_action
  event_data:
    entity_id: binary_sensor.cube_158d0001104272
    action_type: shake_air
action:
  service: homeassistant.turn_off
  entity_id: group.kitchenlights
#  service: tts.google_say
#  entity_id: media_player.squeezebox_radio
#  data:
#    message: 'Cube Shake air'

