
- alias: 'Button single click'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001147e8e
      click_type: single
  action:
    service: cover.close_cover
    entity_id: cover.livingroom_blinds_switch

- alias: 'Button double click'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001147e8e
      click_type: double
  action:
    service: cover.open_cover
    entity_id: cover.livingroom_blinds_switch

- alias: 'Button hold'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001147e8e
      click_type: hold
  action:
    service: cover.set_cover_position
    data:
      entity_id: cover.livingroom_blinds_switch
      position: 75
