- platform: mqtt
  name: "Temperature"
  state_topic: "/airport/temperature"
- platform: mqtt
  name: "Windspeed"
  state_topic: "/airport/windspeed"
  - platform: mqtt
  name: "Windgust"
  state_topic: "/airport/windgust"
  - platform: mqtt
  name: "Winddirection"
  state_topic: "/airport/winddirection"