- platform: mqtt
  name: "Temperature ESSD"
  state_topic: "/airport/temperature"
- platform: mqtt
  name: "Windspeed ESSD"
  state_topic: "/airport/windspeed"
- platform: mqtt
  name: "Windgust ESSD"
  state_topic: "/airport/windgust"
- platform: mqtt
  name: "Winddirection ESSD"
  state_topic: "/airport/winddirection"