- platform: efergy
  app_token: !secret efergy_token
  utc_offset: 120
  monitored_variables:
    - type: current_values
    - type: amount
      period: day
      currency: SEK
  icon: mdi:flash-outline