- platform: mqtt
  state_topic: "nibe/outdoortemp"
  name: 'Nibe 1255 Outdoor temp'
- platform: mqtt
  state_topic: "nibe/outdooraverage"
  name: 'Nibe 1255 Avg Outdoor Temp'
- platform: mqtt
  state_topic: "nibe/degreeminutes"
  name: 'Nibe 1255 Degree minutes'
- platform: mqtt
  state_topic: "nibe/hotgas"
  name: 'Nibe 1255 Hot Gas'
- platform: mqtt
  state_topic: "nibe/hotwatercharging"
  name: 'Nibe 1255 Hot water charging'
- platform: mqtt
  state_topic: "nibe/returntemp"
  name: 'Nibe 1255 Return temp'
- platform: mqtt
  state_topic: "nibe/liquidline"
  name: 'Nibe 1255 Liquid Line'
