- platform: qnap
  host: !secret skarsjocore_ip
  username: !secret qnapuser
  password: !secret qnappass
  verify_ssl: false
#  ssl: true
#  port: 8081
  monitored_conditions:
    - status
    - cpu_usage
    - memory_percent_used
    - network_tx
    - volume_percentage_used
    - drive_smart_status
    - drive_temp
