- alias: "Batteries low"
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id:
      - binary_sensor.cube_158d00010ae6d9_battery
      - binary_sensor.cube_158d0001104272_battery
      - binary_sensor.door_window_sensor_158d000111ed95_battery
      - binary_sensor.door_window_sensor_158d00013fd5b4_battery
      - binary_sensor.motion_sensor_158d00010a9ef1_battery
      - binary_sensor.motion_sensor_158d00012682d3_battery
      - binary_sensor.switch_158d0001147e8e_battery
      - binary_sensor.switch_158d000186e5cd_battery
      - sensor.humidity_158d00010678df_battery
      - sensor.humidity_158d00012cb2f7_battery
      - sensor.humidity_158d00012cb38e_battery
      - sensor.humidity_158d000155c9cc_battery
      - sensor.humidity_158d000155ca89_battery
      - sensor.temperature_158d00010678df_battery
      - sensor.temperature_158d00012cb2f7_battery
      - sensor.temperature_158d00012cb38e_battery
      - sensor.temperature_158d000155c9cc_battery
      - sensor.temperature_158d000155ca89_battery
      - zwave.entrance_multisensor_battery
      - zwave.fibaro_system_fgsd002_smoke_sensor_battery

    value_template: '{{ state.attributes.battery }}'
    below: 20
  action:
    service: notify.slack
    data_template:
      message: >
        {{ trigger.to_state.attributes.friendly_name }}'s battery is low: {{ trigger.to_state.attributes.battery }}%


#todo clearly not working