- alias: 'Telegram bot'
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/ping'
  action:
    - service: notify.telegram
      data:
        message: 'pong'
        data:
          keyboard:
            - '/cam, /home, /kitchenlight'

- alias: 'Cams'
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/cam'
  action:
    - service: notify.telegram
      data:
        title: Cams
        message: 'Doorcam'
        data:
          photo:
          - url: !secret doorcam_url
            username: visitor
            password: !secret doorcam_pw
          - url: !secret grantec_url
            username: visitor             
            password: !secret grandtec_pw  



- alias: 'Whos home'
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/home'
  action:
    - service: notify.telegram
      data:
        message: "{% if is_state('device_tracker.anne_iphone', 'home') %} Anne is at home.\n{% else %} Anne is away.\n{% endif %}
                 {% if is_state('device_tracker.johan_iphone', 'home') %} Johan is at home.\n\n{% else %} Johan is away.\n\n{% endif %}
                 Kitchenlight is {{ states.light.a60rgbw_01.state}} (/kitchenlight)\n"

- alias: 'Kitchenlight'
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/kitchenlight'
  action:
    - service: homeassistant.turn_on
      entity_id: group.kitchenlights
    - delay:
        seconds: 10
    - service: homeassistant.turn_off
      entity_id: group.kitchenlights

