alias: "Entrance Light"
trigger:
  platform: state
  entity_id: binary_sensor.entrance_multisensor_sensor_11_0
  state: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.entrance_multisensor_luminance_11_3
    below: 30
action:
  service: homeassistant.turn_on
  entity_id: switch.entrance_porch_light_switch_2_0
