- alias: "Bedroom lights - Sunset on"
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  condition:
    condition: sun
    before: sunset
    offset: "-00:15:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.bedroomlights
