- alias: "Lights morning on"
  trigger:
    platform: time
    after: "04:30:00"
  condition:
    condition: sun
    before: sunset
  action:
    service: homeassistant.turn_on
    entity_id: group.morningonlights
