alias: "Batteries low"
trigger:
  platform: numeric_state
  entity_id:
  - sensor.entrance_multisensor_temperature_11_1_battery
  - sensor.lounge_smokedetector_general_7_0_battery
  - binary_sensor.bathroom_multisensor_sensor_10_0_battery
  - binary_sensor.entrance_multisensor_sensor_11_0_battery
  - binary_sensor.stairs_smokedetector_sensor_15_0_battery
  - sensor.lounge_smokedetector_alarm_level_7_0_battery
  value_template: '{{ state.attributes.battery }}'
  below: 50
action:
  service: notify.slack
  data_template:
    message: >
      {{ trigger.to_state.attributes.friendly_name }}'s battery is low: {{ trigger.to_state.attributes.battery }}%
