alias: "Entrance Light"
trigger:
  platform: state
  entity_id: binary_sensor.entrance_multisensor_sensor_11
  from: 'off'
  to: 'on'
condition:
  - condition: numeric_state
    entity_id: sensor.entrance_multisensor_luminance_11
    below: 40
action:
  service: homeassistant.turn_on
  entity_id: script.timed_light
