alias: 'Update Available Notifications'
trigger:
  platform: state
  entity_id: updater.updater
action:
  service: notify.slack
  data:
    message: '@johan - Update for Home Assistant is available.'
