- alias: "Den motion light on"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00010a9ef1
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 3.5
#  condition:
#    platform: numeric_state
#    entity_id: sun.sun
#    value_template: '{{ state.attributes.elevation }}'
#    below: 3.5
  action:
    service: homeassistant.turn_on
    entity_id: light.denceiling

- alias: "Den motion light off"
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00010a9ef1
    to: 'off'
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: light.denceiling
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: light.denceiling
