homeassistant:

switch:
  - platform: broadlink
    host: 10.11.12.23
    mac: '34:ea:34:b2:f7:fd'
#    type: rm_mini
    switches:
      livingroom_receiver_power:
        friendly_name: "Pioneer Reciever Power"
        command_on: 'JgCwAQABGYkTMhERETQREhASETQRERE0ERERNRIQETQRNBASETQRERESERERNBE0ETQQEhMQEBIQNRE0EREREhMPETQRNBE0EAADdAABGIoRNBERETQUDhESEDUQEhE0ERIQNRASETQRNBASETQUDhESEBIRNBE0ETQRERQPExAQNBE0EREREhQOETQTMhA1EQADUQABFY0QNRASEzIREhIQETQUDhQxExASMhQPFDETMhASETQREhIQEw8TMhQxEzITDxESEw8RNBE0EREREhESEjMSMhMyEwADcgABGIoRNBASETQRERESEDUQEhE0EBMTMRMQEzITMhIQEzITDxESEhATMhMyEDUTEBIQEw8UMRMyExASEBMPEzITMhMyEwADTwABFowRNBESEDUTDxESEDQREhMyERERNBESEDQTMhESEjMQEhASERIQNRE0ETQRERESEBIRNBE0EhAREhMPEzITMhMyEwADcgABFowQNRQOEjMRERMQETQTDxMyEw8TMhESEDURNBMPETQREhASFA4RNBE0ETQREhMPEBIRNRA0ERIREhASEzIQNRA0EQANBQAAAAAAAAAA'
        command_off: 'JgCwAQABGYkTMhERETQREhASETQRERE0ERERNRIQETQRNBASETQRERESERERNBE0ETQQEhMQEBIQNRE0EREREhMPETQRNBE0EAADdAABGIoRNBERETQUDhESEDUQEhE0ERIQNRASETQRNBASETQUDhESEBIRNBE0ETQRERQPExAQNBE0EREREhQOETQTMhA1EQADUQABFY0QNRASEzIREhIQETQUDhQxExASMhQPFDETMhASETQREhIQEw8TMhQxEzITDxESEw8RNBE0EREREhESEjMSMhMyEwADcgABGIoRNBASETQRERESEDUQEhE0EBMTMRMQEzITMhIQEzITDxESEhATMhMyEDUTEBIQEw8UMRMyExASEBMPEzITMhMyEwADTwABFowRNBESEDUTDxESEDQREhMyERERNBESEDQTMhESEjMQEhASERIQNRE0ETQRERESEBIRNBE0EhAREhMPEzITMhMyEwADcgABFowQNRQOEjMRERMQETQTDxMyEw8TMhESEDURNBMPETQREhASFA4RNBE0ETQREhMPEBIRNRA0ERIREhASEzIQNRA0EQANBQAAAAAAAAAA'
      livingroom_receiver_source_squeezebox:
        friendly_name: "Pioneer Reciever Squeezebox"
        command_on: 'JgBAAgABFYwRNBIREDURERIQEjMSERE0ERESNA8TEDQRNBATEDQSERIRERERERE0EhASERIRETMRNBA1EjMSEBE0EjMSMxEREgADcwABFY0RMxIREjMRERMQETMSERA1EhASMxIRETMSMxIREjMSEBIQEhESEBE0EhEQEhIRETQQNBIzEjMSEREzEjMSMxESEQADUQABFY0RNBASEjMRERESEDUQEhIzEhARNBIRETQRNBEREDUREhEREhEQEhE0ERESEREREjMQNRE0EDUREhA0EDUSMxEREgADcwABFowRNBERETQSEBIRETQRERIzERESNBASEjMSMxASETQSEBIREhAREhE0ERIRERESEDQQNRIzEjMRERIzETQSMxESEQADUQABFYwSMxIREjMREhERETMREhIzEhASMxIRETQRMxIREjMREhESDxISERE0ERERERESETQSMxE0EDURERE0EDUSMxASEgADcwABFowSMxERETQSERASEjMREhEzEhERNBESEDQRNBATEDQSERIREREQEhIzEhEQEhIRETMRNRA0EjQPExE0ETMRNBESEAADUwABFYwSMxIREDUREhASEDQSERE0ERESMxIREDUQNREREjMSEBIREBMRERE0ERESEREREjMSMxE0ETQRERIzEjMQNRESEAADdQABFosSMxIRETQQExERETQRERE0ERESMxISETMRNBASETURERASEhERERIzEhASEREREjMRNBIzEjMREhEzETQSMxESEQANBRIREhAREhE0'
        command_off: 'JgBAAgABFYwRNBIREDURERIQEjMSERE0ERESNA8TEDQRNBATEDQSERIRERERERE0EhASERIRETMRNBA1EjMSEBE0EjMSMxEREgADcwABFY0RMxIREjMRERMQETMSERA1EhASMxIRETMSMxIREjMSEBIQEhESEBE0EhEQEhIRETQQNBIzEjMSEREzEjMSMxESEQADUQABFY0RNBASEjMRERESEDUQEhIzEhARNBIRETQRNBEREDUREhEREhEQEhE0ERESEREREjMQNRE0EDUREhA0EDUSMxEREgADcwABFowRNBERETQSEBIRETQRERIzERESNBASEjMSMxASETQSEBIREhAREhE0ERIRERESEDQQNRIzEjMRERIzETQSMxESEQADUQABFYwSMxIREjMREhERETMREhIzEhASMxIRETQRMxIREjMREhESDxISERE0ERERERESETQSMxE0EDURERE0EDUSMxASEgADcwABFowSMxERETQSERASEjMREhEzEhERNBESEDQRNBATEDQSERIREREQEhIzEhEQEhIRETMRNRA0EjQPExE0ETMRNBESEAADUwABFYwSMxIREDUREhASEDQSERE0ERESMxIREDUQNREREjMSEBIREBMRERE0ERESEREREjMSMxE0ETQRERIzEjMQNRESEAADdQABFosSMxIRETQQExERETQRERE0ERESMxISETMRNBASETURERASEhERERIzEhASEREREjMRNBIzEjMREhEzETQSMxESEQANBRIREhAREhE0'

#script:
#  livingroom_squeezebox_on:
#    sequence:
#      service: homeassistant.turn_on
#      data:
#        entity_id: switch.pioneer_reciever_power
#  air_cleaner_auto:
#    sequence:
#      service: homeassistant.turn_on
#      data:
#        entity_id: switch.air_cleaner_auto
#
#
#group:
#  air:
#    name: Air Cleaner Bedroom
#    entities:
#      - input_text.air_tiles
#
#automation:
#  - alias: Air Cleaner To Quiet at 21
#    initial_state: 'on'
#    trigger:
#      - platform: time
#        at: '21:00:00'
#    action:
#      - service: homeassistant.turn_on
#        entity_id: switch.air_cleaner_quiet
#
#  - alias: Air Cleaner To Auto At 11
#    initial_state: 'on'
#    trigger:
#      - platform: time
#        at: '11:00:00'
#    action:
#      - service: homeassistant.turn_on
#        entity_id: switch.air_cleaner_auto
#