homeassistant:

  customize:
    input_select.log_level:
      icon: mdi:console
      friendly_name: Set log level

input_select:
  log_level:
    name: Log Level
    options:
      - critical
      - fatal
      - error
      - warning
      - warn
      - info
      - debug
      - notset
    initial: warn

automation:
  - alias: Log Level
    trigger:
      platform: state
      entity_id: input_select.log_level
    action:
      service: logger.set_level
      data_template:
        homeassistant.components: "{{ trigger.to_state.state }}"

# doesn't work to reuse groups.. Howto get this into an existing?
#group:
#  Admin:
#    name: Set log level
#    entitites:
#      - input_select.log_level