homeassistant:

  customize:
    sensor.smhi_temperatur:
      icon: mdi:temperature-celsius
    sensor.smhi_luftfuktighet:
      icon: mdi:water-percent
    sensor.smhi_lufttryck:
      icon: mdi:gauge
    sensor.smhi_sikt:
      icon: mdi:mixcloud
    sensor.smhi_vindhastighet:
      icon: mdi:weather-windy
    sensor.smhi_vindbyar:
      icon: mdi:weather-windy
    sensor.smhi_vindriktning:
      icon: mdi:sign-direction
    sensor.smhi_chans_for_aska:
      icon: mdi:weather-lightning
    sensor.ksd_vindriktning_text:
      icon: mdi:sign-direction
    sensor.ksd_vadersymboler_text:
      icon: mdi:weather-partlycloudy
    sensor.ksd_nederbordstyp_text:
      icon: mdi:weather-partlycloudy
    sensor.smhi_min_nederbord:
      icon: mdi:weather-fog
    sensor.smhi_snittnederbord:
      icon: mdi:weather-fog
    sensor.smhi_max_nederbord:
      icon: mdi:weather-fog



template:
  - platform: template
    sensors:
      smhi_vindriktning_text:
        friendly_name: 'SMHI Vindriktning'
        value_template: >-
          {%if states.sensor.smhi_vindriktning.state | float<=11 %}Nord
          {% elif states.sensor.smhi_vindriktning.state | float>348 %}Nord
          {% elif states.sensor.smhi_vindriktning.state | float<=34 | float>11 %}Nord Nord Öst
          {% elif states.sensor.smhi_vindriktning.state | float<=56 | float>34 %}Nord Öst
          {% elif states.sensor.smhi_vindriktning.state | float<=79 | float>56 %}Öst Nord Öst
          {% elif states.sensor.smhi_vindriktning.state | float<=101 | float>79 %}Öst
          {% elif states.sensor.smhi_vindriktning.state | float<=124 | float>101 %}Öst Syd Öst
          {% elif states.sensor.smhi_vindriktning.state | float<=146 | float>124 %}Syd Öst
          {% elif states.sensor.smhi_vindriktning.state | float<=169 | float>146 %}Syd Syd Öst
          {% elif states.sensor.smhi_vindriktning.state | float<=191 | float>169 %}Syd
          {% elif states.sensor.smhi_vindriktning.state | float<=214 | float>191 %}Syd Syd Väst
          {% elif states.sensor.smhi_vindriktning.state | float<=236 | float>214 %}Syd Väst
          {% elif states.sensor.smhi_vindriktning.state | float<=259 | float>236 %}Väst Syd Väst
          {% elif states.sensor.smhi_vindriktning.state | float<=281 | float>259 %}Väst
          {% elif states.sensor.smhi_vindriktning.state | float<=304 | float>281 %}Väst Nord Väst
          {% elif states.sensor.smhi_vindriktning.state | float<=326 | float>304 %}Väst Nord Väst
          {% elif states.sensor.smhi_vindriktning.state | float<=348 | float>326 %}Nord Nord Väst
          {%- endif %}
      smhi_vadersymboler_text:
        friendly_name: 'SMHI Vädersymboler'
        value_template: >-
          {%if states.sensor.smhi_vadersymboler.state | int==1 %}Klart himmel
          {% elif states.sensor.smhi_vadersymboler.state | int==2 %}Molntussar
          {% elif states.sensor.smhi_vadersymboler.state | int==3 %}Uppsprucket molntäcke
          {% elif states.sensor.smhi_vadersymboler.state | int==4 %}Nästan mulet
          {% elif states.sensor.smhi_vadersymboler.state | int==5 %}Mulet
          {% elif states.sensor.smhi_vadersymboler.state | int==6 %}Riktigt tokigenmulet
          {% elif states.sensor.smhi_vadersymboler.state | int==7 %}Dimma
          {% elif states.sensor.smhi_vadersymboler.state | int==8 %}Lätta Regnskurar
          {% elif states.sensor.smhi_vadersymboler.state | int==9 %}Medel Regnskurar
          {% elif states.sensor.smhi_vadersymboler.state | int==10 %}Kraftiga Regnskurar
          {% elif states.sensor.smhi_vadersymboler.state | int==11 %}Åskoväder
          {% elif states.sensor.smhi_vadersymboler.state | int==12 %}Lätt Snöblandade regnskurar
          {% elif states.sensor.smhi_vadersymboler.state | int==13 %}Medel Snöblandade regnskurar
          {% elif states.sensor.smhi_vadersymboler.state | int==14 %}Kraftiga Snöblandade regnskurar
          {% elif states.sensor.smhi_vadersymboler.state | int==15 %}Lätta Snöbyar
          {% elif states.sensor.smhi_vadersymboler.state | int==16 %}Medel Snöbyar
          {% elif states.sensor.smhi_vadersymboler.state | int==17 %}Kraftligta Snöbyar
          {% elif states.sensor.smhi_vadersymboler.state | int==18 %}Lätt Regn
          {% elif states.sensor.smhi_vadersymboler.state | int==19 %}Medel Regn
          {% elif states.sensor.smhi_vadersymboler.state | int==20 %}Kraftligt Regn
          {% elif states.sensor.smhi_vadersymboler.state | int==21 %}Åska
          {% elif states.sensor.smhi_vadersymboler.state | int==22 %}Lätt Snöblandat regn
          {% elif states.sensor.smhi_vadersymboler.state | int==23 %}Medel Snöblandat regn
          {% elif states.sensor.smhi_vadersymboler.state | int==24 %}Kraftigt Snöblandat regn
          {% elif states.sensor.smhi_vadersymboler.state | int==25 %}Lätt Snöfall
          {% elif states.sensor.smhi_vadersymboler.state | int==26 %}Medel Snöfall
          {% elif states.sensor.smhi_vadersymboler.state | int==27 %}Kraftlig Snöfall
          {% elif states.sensor.smhi_vadersymboler.state | int>=28 %}Error
          {%- endif %}

      smhi_nederbordstyp_text:
        friendly_name: 'SMHI Nederbördstyp'
        value_template: >-
          {%if states.sensor.smhi_typ_av_nederbord.state | int==0 %}Ingen nederbörd
          {% elif states.sensor.smhi_typ_av_nederbord.state | int==1 %}Snö
          {% elif states.sensor.smhi_typ_av_nederbord.state | int==2 %}Snöblandat Regn
          {% elif states.sensor.smhi_typ_av_nederbord.state | int==3 %}Regn
          {% elif states.sensor.smhi_typ_av_nederbord.state | int==4 %}Duggregn
          {% elif states.sensor.smhi_typ_av_nederbord.state | int==5 %}Underkylt Regn
          {% elif states.sensor.smhi_typ_av_nederbord.state | int==6 %}Underkylt Duggregn
          {% elif states.sensor.smhi_typ_av_nederbord.state | int>=7 %}Error
          {%- endif %}
      smhi_sno_min:
        friendly_name: 'SMHI Snö min'
        unit_of_measurement: "cm"
        icon_template: mdi:weather-snowy
        value_template: >-
          {%if states.sensor.smhi_temperatur.state | float>-1 | float<=0 %}{{ states.sensor.smhi_min_nederbord.state | float * 1 }}
          {% elif states.sensor.smhi_temperatur.state | float>-2 | float<=-1 %}{{ states.sensor.smhi_min_nederbord.state | float * 1.2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-3 | float<=-2 %}{{ states.sensor.smhi_min_nederbord.state | float * 1.3 }}
          {% elif states.sensor.smhi_temperatur.state | float>-4 | float<=-3 %}{{ states.sensor.smhi_min_nederbord.state | float * 1.4 }}
          {% elif states.sensor.smhi_temperatur.state | float>-5 | float<=-4 %}{{ states.sensor.smhi_min_nederbord.state | float * 1.5 }}
          {% elif states.sensor.smhi_temperatur.state | float>-6 | float<=-5 %}{{ states.sensor.smhi_min_nederbord.state | float * 1.7 }}
          {% elif states.sensor.smhi_temperatur.state | float>-7 | float<=-6 %}{{ states.sensor.smhi_min_nederbord.state | float * 1.8 }}
          {% elif states.sensor.smhi_temperatur.state | float>-8 | float<=-7 %}{{ states.sensor.smhi_min_nederbord.state | float * 2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-9 | float<=-8 %}{{ states.sensor.smhi_min_nederbord.state | float * 2.2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-10 | float<=-9 %}{{ states.sensor.smhi_min_nederbord.state | float * 2.4 }}
          {% elif states.sensor.smhi_temperatur.state | float>-11 | float<=-10 %}{{ states.sensor.smhi_min_nederbord.state | float * 2.7 }}
          {% elif states.sensor.smhi_temperatur.state | float>-12 | float<=-11 %}{{ states.sensor.smhi_min_nederbord.state | float * 3 }}
          {% elif states.sensor.smhi_temperatur.state | float>-13 | float<=-12 %}{{ states.sensor.smhi_min_nederbord.state | float * 3.4 }}
          {% elif states.sensor.smhi_temperatur.state | float>-14 | float<=-13 %}{{ states.sensor.smhi_min_nederbord.state | float * 3.7 }}
          {% elif states.sensor.smhi_temperatur.state | float>-15 | float<=-14 %}{{ states.sensor.smhi_min_nederbord.state | float * 4.2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-16 | float<=-15 %}{{ states.sensor.smhi_min_nederbord.state | float * 4.6 }}
          {% elif states.sensor.smhi_temperatur.state | float>-17 | float<=-16 %}{{ states.sensor.smhi_min_nederbord.state | float * 5.1 }}
          {% elif states.sensor.smhi_temperatur.state | float>-18 | float<=-17 %}{{ states.sensor.smhi_min_nederbord.state | float * 5.5 }}
          {% elif states.sensor.smhi_temperatur.state | float>-19 | float<=-18 %}{{ states.sensor.smhi_min_nederbord.state | float * 5.9 }}
          {% elif states.sensor.smhi_temperatur.state | float>-20 | float<=-19 %}{{ states.sensor.smhi_min_nederbord.state | float * 6.2 }}
          {% elif states.sensor.smhi_temperatur.state | float<=-20 %}{{ states.sensor.smhi_min_nederbord.state | float * 6.4 }}
          {%- endif %}
      smhi_sno_max:
        friendly_name: 'SMHI Snö max'
        unit_of_measurement: "cm"
        icon_template: mdi:weather-snowy
        value_template: >-
          {%if states.sensor.smhi_temperatur.state | float>-1 | float<=0 %}{{ states.sensor.smhi_max_nederbord.state | float * 1 }}
          {% elif states.sensor.smhi_temperatur.state | float>-2 | float<=-1 %}{{ states.sensor.smhi_max_nederbord.state | float * 1.2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-3 | float<=-2 %}{{ states.sensor.smhi_max_nederbord.state | float * 1.3 }}
          {% elif states.sensor.smhi_temperatur.state | float>-4 | float<=-3 %}{{ states.sensor.smhi_max_nederbord.state | float * 1.4 }}
          {% elif states.sensor.smhi_temperatur.state | float>-5 | float<=-4 %}{{ states.sensor.smhi_max_nederbord.state | float * 1.5 }}
          {% elif states.sensor.smhi_temperatur.state | float>-6 | float<=-5 %}{{ states.sensor.smhi_max_nederbord.state | float * 1.7 }}
          {% elif states.sensor.smhi_temperatur.state | float>-7 | float<=-6 %}{{ states.sensor.smhi_max_nederbord.state | float * 1.8 }}
          {% elif states.sensor.smhi_temperatur.state | float>-8 | float<=-7 %}{{ states.sensor.smhi_max_nederbord.state | float * 2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-9 | float<=-8 %}{{ states.sensor.smhi_max_nederbord.state | float * 2.2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-10 | float<=-9 %}{{ states.sensor.smhi_max_nederbord.state | float * 2.4 }}
          {% elif states.sensor.smhi_temperatur.state | float>-11 | float<=-10 %}{{ states.sensor.smhi_max_nederbord.state | float * 2.7 }}
          {% elif states.sensor.smhi_temperatur.state | float>-12 | float<=-11 %}{{ states.sensor.smhi_max_nederbord.state | float * 3 }}
          {% elif states.sensor.smhi_temperatur.state | float>-13 | float<=-12 %}{{ states.sensor.smhi_max_nederbord.state | float * 3.4 }}
          {% elif states.sensor.smhi_temperatur.state | float>-14 | float<=-13 %}{{ states.sensor.smhi_max_nederbord.state | float * 3.7 }}
          {% elif states.sensor.smhi_temperatur.state | float>-15 | float<=-14 %}{{ states.sensor.smhi_max_nederbord.state | float * 4.2 }}
          {% elif states.sensor.smhi_temperatur.state | float>-16 | float<=-15 %}{{ states.sensor.smhi_max_nederbord.state | float * 4.6 }}
          {% elif states.sensor.smhi_temperatur.state | float>-17 | float<=-16 %}{{ states.sensor.smhi_max_nederbord.state | float * 5.1 }}
          {% elif states.sensor.smhi_temperatur.state | float>-18 | float<=-17 %}{{ states.sensor.smhi_max_nederbord.state | float * 5.5 }}
          {% elif states.sensor.smhi_temperatur.state | float>-19 | float<=-18 %}{{ states.sensor.smhi_max_nederbord.state | float * 5.9 }}
          {% elif states.sensor.smhi_temperatur.state | float>-20 | float<=-19 %}{{ states.sensor.smhi_max_nederbord.state | float * 6.2 }}
          {% elif states.sensor.smhi_temperatur.state | float<=-20 %}{{ states.sensor.smhi_max_nederbord.state | float * 6.4 }}
          {%- endif %}


sensor:
  #Fri sikt
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI sikt
    unit_of_measurement: "km"
    value_template: "{{ value_json['vis'] }}"

  # Lufftryck
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI lufttryck
    unit_of_measurement: "hPa"
    value_template: "{{ value_json['msl'] | round(1) }}"

  #Luftfuktighet
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI luftfuktighet
    unit_of_measurement: "%"
    value_template: "{{ value_json['r'] | round(1) }}"

  #Temperatur
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI temperatur
    unit_of_measurement: "°C"
    value_template: "{{ value_json['t'] | round(1) }}"

  #Vindriktning
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI vindriktning
    unit_of_measurement: "°"
    value_template: "{{ value_json['wd'] }}"

  #Vindhastighet
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI vindhastighet
    unit_of_measurement: "m/s"
    value_template: "{{ value_json['ws'] }}"

  #Vindbyar
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI vindbyar
    unit_of_measurement: "m/s"
    value_template: "{{ value_json['gust'] | round(1) }}"

  #Chans för åska
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI chans för åska
    unit_of_measurement: "%"
    value_template: "{{ value_json['tstm'] }}"

  #Min Nederbörd
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI min nederbörd
    unit_of_measurement: "mm"
    value_template: "{{ value_json['pmin'] | round(1) }}"

  #Snittnederbörd
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI snittnederbörd
    unit_of_measurement: "mm"
    value_template: "{{ value_json['pmedian'] | round(1) }}"

  #Max Nederbörd
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI max nederbörd
    unit_of_measurement: "mm"
    value_template: "{{ value_json['pmax'] | round(1) }}"

  #Typ av nederbörd
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI typ av nederbörd
    unit_of_measurement: "typ"
    value_template: "{{ value_json['pcat'] }}"

  #Vädersymboler
  - platform: mqtt
    state_topic: 'SMHI/values'
    name: SMHI vädersymboler
    unit_of_measurement: "typ"
    value_template: "{{ value_json['Wsymb2'] }}"





group:
  SMHI:
    - sensor.smhi_temperatur
    - sensor.smhi_chans_for_aska
    - sensor.smhi_luftfuktighet
    - sensor.smhi_lufttryck
    - sensor.smhi_max_nederbord
    - sensor.smhi_snittnederbord
    - sensor.smhi_min_nederbord
    - sensor.smhi_sikt
    - sensor.smhi_vindbyar
    - sensor.smhi_vindhastighet
    - sensor.smhi_vindriktning
    - sensor.smhi_nederbordstyp_text
    - sensor.smhi_vindriktning_text
    - sensor.smhi_sno_max
    - sensor.smhi_sno_min
    - sensor.smhi_vadersymboler_text